### ISSUE TITLE
All builds are broken

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.Sessions#32]
```
Error in test testUncommittable (Products.Transience.tests.testTransactionHelper.TestTransactionHelper)
Traceback (most recent call last):
  File "/opt/python/2.7.15/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/travis/build/zopefoundation/Products.Sessions/src/Products/Transience/tests/testTransactionHelper.py", line 30, in testUncommittable
    makeTransactionUncommittable(self.t, "test")
  File "/home/travis/build/zopefoundation/Products.Sessions/src/Products/Transience/TransactionHelper.py", line 41, in __init__
    transaction.register(self)
AttributeError: 'Transaction' object has no attribute 'register'
```

https://travis-ci.org/github/zopefoundation/Products.Sessions

@icemac mentioned in the wrap up of the Zope sprint, that this is no easy fix

**Comment by icemac** [comment]
Currently `Products.Sessions` is  not compatible with `transaction >= 3`.
See https://github.com/zopefoundation/transaction/issues/89 for details.
